### Data set is called "E:\AMIT - Assignments and Materials\AI ONL 104\Data Preprocessing & Visulization\Pandas Practice assignment\Data\bi.csv"

In [18]:
import pandas as pd

In [34]:
df = pd.read_csv(r"E:\AMIT - Assignments and Materials\AI ONL 104\Data Preprocessing & Visulization\Pandas Practice assignment\Data\bi.csv", encoding="ISO-8859-1")
df

fNAME      lNAME  Age  gender       country  residence  entryEXAM  \
0   Christina     Binger   44  Female        Norway    Private         72   
1        Alex   Walekhwa   60       M         Kenya    Private         79   
2      Philip        Leo   25    Male        Uganda  Sognsvann         55   
3       Shoni  Hlongwane   22       F           Rsa  Sognsvann         40   
4       Maria   Kedibone   23  Female  South Africa  Sognsvann         65   
..        ...        ...  ...     ...           ...        ...        ...   
72      Clara    Bernard   43  Female        France    Private         80   
73     Julian    Nielsen   31    Male       Denmark  Sognsvann         90   
74     Sophie      Brown   33  Female            UK  Sognsvann         96   
75       Leon      Bauer   35    Male       Germany  Sognsvann         90   
76   Mohammed      Salim   31    Male        Somali  Sognsvann         35   

   prevEducation  studyHOURS  Python  DB  
0        Masters         158    59.0  55  
1        Diploma         150    60.0  75  
2     HighSchool         130    74.0  50  
3    High School         120     NaN  44  
4    High School         122    91.0  80  
..           ...         ...     ...  ..  
72     Bachelors         150    75.0  43  
73       Masters         158    84.0  83  
74       Masters         158    85.0  90  
75       Masters         160    87.0  74  
76       Masters         144    72.0  90  

[77 rows x 11 columns]

# part One

In [35]:
# first 5 min

df.shape

(77, 11)

In [36]:
df.columns

Index(['fNAME', 'lNAME', 'Age', 'gender', 'country', 'residence', 'entryEXAM',
       'prevEducation', 'studyHOURS', 'Python', 'DB'],
      dtype='object')

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   fNAME          77 non-null     object 
 1   lNAME          77 non-null     object 
 2   Age            77 non-null     int64  
 3   gender         77 non-null     object 
 4   country        77 non-null     object 
 5   residence      77 non-null     object 
 6   entryEXAM      77 non-null     int64  
 7   prevEducation  77 non-null     object 
 8   studyHOURS     77 non-null     int64  
 9   Python         75 non-null     float64
 10  DB             77 non-null     int64  
dtypes: float64(1), int64(4), object(6)
memory usage: 6.7+ KB


In [38]:
df.describe()

Age  entryEXAM  studyHOURS     Python          DB
count  77.000000  77.000000   77.000000  75.000000   77.000000
mean   35.207792  76.753247  149.714286  75.853333   69.467532
std    10.341966  16.475784   12.743272  15.410328   17.033701
min    21.000000  28.000000  114.000000  15.000000   30.000000
25%    27.000000  69.000000  144.000000  71.000000   56.000000
50%    33.000000  80.000000  156.000000  81.000000   71.000000
75%    42.000000  90.000000  158.000000  85.000000   83.000000
max    71.000000  98.000000  160.000000  91.000000  100.000000

In [39]:
df.head()

fNAME      lNAME  Age  gender       country  residence  entryEXAM  \
0  Christina     Binger   44  Female        Norway    Private         72   
1       Alex   Walekhwa   60       M         Kenya    Private         79   
2     Philip        Leo   25    Male        Uganda  Sognsvann         55   
3      Shoni  Hlongwane   22       F           Rsa  Sognsvann         40   
4      Maria   Kedibone   23  Female  South Africa  Sognsvann         65   

  prevEducation  studyHOURS  Python  DB  
0       Masters         158    59.0  55  
1       Diploma         150    60.0  75  
2    HighSchool         130    74.0  50  
3   High School         120     NaN  44  
4   High School         122    91.0  80

## Data Cleaning

In [40]:
#detect nulls 
df.isnull().sum()

fNAME            0
lNAME            0
Age              0
gender           0
country          0
residence        0
entryEXAM        0
prevEducation    0
studyHOURS       0
Python           2
DB               0
dtype: int64

In [41]:
df['Python'].isnull().sum()

np.int64(2)

In [42]:
# drop nulls in Python column
df = df.dropna(subset=['Python'])
df.isnull().sum()

fNAME            0
lNAME            0
Age              0
gender           0
country          0
residence        0
entryEXAM        0
prevEducation    0
studyHOURS       0
Python           0
DB               0
dtype: int64

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 75 entries, 0 to 76
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   fNAME          75 non-null     object 
 1   lNAME          75 non-null     object 
 2   Age            75 non-null     int64  
 3   gender         75 non-null     object 
 4   country        75 non-null     object 
 5   residence      75 non-null     object 
 6   entryEXAM      75 non-null     int64  
 7   prevEducation  75 non-null     object 
 8   studyHOURS     75 non-null     int64  
 9   Python         75 non-null     float64
 10  DB             75 non-null     int64  
dtypes: float64(1), int64(4), object(6)
memory usage: 7.0+ KB


In [44]:
# detect duplicates
df.duplicated().sum()

np.int64(0)

In [45]:
df['gender'].unique()

array(['Female', 'M', 'Male', 'female', 'male'], dtype=object)

In [46]:
# change array(['Female', 'M', 'Male', 'female', 'male'] to Male and Female
df['gender'] = df['gender'].replace(['M', 'male'], 'Male').replace(['F', 'female'], 'Female')


C:\Users\DELL\AppData\Local\Temp\ipykernel_20092\1300426250.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gender'] = df['gender'].replace(['M', 'male'], 'Male').replace(['F', 'female'], 'Female')


In [47]:
df['gender'].unique()

array(['Female', 'Male'], dtype=object)

In [48]:
df

fNAME     lNAME  Age  gender       country     residence  entryEXAM  \
0   Christina    Binger   44  Female        Norway       Private         72   
1        Alex  Walekhwa   60    Male         Kenya       Private         79   
2      Philip       Leo   25    Male        Uganda     Sognsvann         55   
4       Maria  Kedibone   23  Female  South Africa     Sognsvann         65   
5      Hannah    Hansen   25  Female         Norge  BI Residence         66   
..        ...       ...  ...     ...           ...           ...        ...   
72      Clara   Bernard   43  Female        France       Private         80   
73     Julian   Nielsen   31    Male       Denmark     Sognsvann         90   
74     Sophie     Brown   33  Female            UK     Sognsvann         96   
75       Leon     Bauer   35    Male       Germany     Sognsvann         90   
76   Mohammed     Salim   31    Male        Somali     Sognsvann         35   

   prevEducation  studyHOURS  Python  DB  
0        Masters         158    59.0  55  
1        Diploma         150    60.0  75  
2     HighSchool         130    74.0  50  
4    High School         122    91.0  80  
5    High School         130    88.0  59  
..           ...         ...     ...  ..  
72     Bachelors         150    75.0  43  
73       Masters         158    84.0  83  
74       Masters         158    85.0  90  
75       Masters         160    87.0  74  
76       Masters         144    72.0  90  

[75 rows x 11 columns]

In [51]:
df['fNAME'].unique()

array(['Christina', 'Alex', 'Philip', 'Maria', 'Hannah', 'Ole', 'Lars',
       'Bjørn', 'Sofie', 'Emma', 'Solveig', 'Odd', 'Grethe', 'Marco',
       'Ingrid', 'Hanna', 'Jorunn', 'Sebastian', 'Camilla', 'Prof',
       'Kristine', 'Carmen', 'Gunnar', 'Gerd', 'Aisha', 'Kato',
       'Nansubuga', 'Joakim', 'Don', 'Perry', 'Line', 'Thor', 'Petter',
       'Sindre', 'Simen', 'Bjørg', 'Trond', 'Emily', 'Unni', 'Ruth',
       'Inger', 'Peninah', 'Berit', 'Jenny', 'Thea', 'Dag', 'Mwanaidi',
       'Chinedu', 'Irene', 'Marianne', 'Jens', 'Morten', 'Karoline',
       'Ola', 'Tore', 'Caroline', 'Silvia', 'Valentino', 'Peter', 'Anna',
       'Lucas', 'Marie', 'Thomas', 'Maximilan', 'Clara', 'Julian',
       'Sophie', 'Leon', 'Mohammed'], dtype=object)

In [52]:
df['lNAME'].unique()

array(['Binger', 'Walekhwa', 'Leo', 'Kedibone', 'Hansen', 'Johansen',
       'Olsen', 'Larsen', 'Jensen', 'de Vries', 'Eliassen', 'Knudsen',
       'Myklebust', 'Rossi', 'Eide', 'Andresen', 'Kristiansen',
       'Mikkelsen', 'Birkeland', 'Isaksen', 'Berg', 'Rodríguez', 'Ahmed',
       'Brekke', 'Bakken', 'Nakaweesi', 'Muwanguzi', 'Nakalema',
       'Edvardsen', 'Pettersen', 'Rønning', 'Næss', 'Sandvik',
       'Ellingsen', 'Myhre', 'Fredriksen', 'Karlsen', 'Thompson',
       'Jacobsen', 'Pedersen', 'Kristoffersen', 'Knutsen', 'Arnesen',
       'Ali', 'Morison', 'Strømertan', 'Okafor', 'Ruud', 'Lunde', 'Bakke',
       'Abrahamsen', 'Narocho', 'Ojiambo', 'Kubebea', 'Müller', 'Schmidt',
       'Dubois', 'García', 'Janssen', 'Martini', 'Bernard', 'Nielsen',
       'Brown', 'Bauer', 'Salim'], dtype=object)

In [53]:
df['Age'].unique()

array([44, 60, 25, 23, 27, 29, 31, 33, 34, 36, 38, 40, 42, 43, 45, 47, 48,
       50, 22, 24, 26, 28, 30, 32, 35, 37, 39, 41, 46, 71, 21, 69])

In [54]:
df['gender'].unique()

array(['Female', 'Male'], dtype=object)

In [55]:
df['country'].unique()

array(['Norway', 'Kenya', 'Uganda', 'South Africa', 'Norge', 'norway',
       'Denmark', 'Netherlands', 'Italy', 'Spain', 'UK', 'Somali',
       'Nigeria', 'Germany', 'France'], dtype=object)

In [56]:
df['residence'].unique()

array(['Private', 'Sognsvann', 'BI Residence', 'BI-Residence',
       'BIResidence', 'BI_Residence'], dtype=object)

In [58]:
df['entryEXAM'].unique()

array([72, 79, 55, 65, 66, 90, 89, 88, 85, 70, 91, 77, 80, 81, 86, 75, 95,
       45, 50, 78, 82, 92, 76, 30, 98, 68, 96, 54, 69, 28, 94, 73, 83, 74,
       35])

In [59]:
df['prevEducation'].unique()

array(['Masters', 'Diploma', 'HighSchool', 'High School', 'Bachelors',
       'Barrrchelors', 'diploma', 'DIPLOMA', 'Diplomaaa', 'Doctorate'],
      dtype=object)

In [60]:
df['prevEducation'] = df['prevEducation'].replace(['diploma', 'DIPLOMA','Diplomaaa'], 'Diploma').replace(['High School'], 'HighSchool').replace(['Barrrchelors'], 'Bachelors')

C:\Users\DELL\AppData\Local\Temp\ipykernel_20092\4147670745.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['prevEducation'] = df['prevEducation'].replace(['diploma', 'DIPLOMA','Diplomaaa'], 'Diploma').replace(['High School'], 'HighSchool').replace(['Barrrchelors'], 'Bachelors')


In [61]:
df['prevEducation'].unique()

array(['Masters', 'Diploma', 'HighSchool', 'Bachelors', 'Doctorate'],
      dtype=object)

In [62]:
df['studyHOURS'].unique()

array([158, 150, 130, 122, 156, 160, 144, 152, 148, 116, 114, 140, 142,
       154, 120, 136, 124, 138])

In [63]:
df['Python'].unique()

array([59., 60., 74., 91., 88., 80., 85., 83., 79., 70., 75., 87., 76.,
       84., 33., 30., 61., 82., 66., 81., 31., 90., 69., 57., 86., 78.,
       48., 45., 15., 63., 72.])

In [64]:
df['DB'].unique()

array([ 55,  75,  50,  80,  59,  91,  60,  89,  90,  58,  99,  76,  77,
        82,  78,  73,  30,  56,  65,  83,  88,  69,  79,  45,  42,  74,
        33,  92,  86,  62,  70,  47,  67, 100,  61,  46,  68,  71,  43])