# train.csv

In [115]:
import pandas as pd

In [116]:
df = pd.read_csv(r"E:\AMIT - Assignments and Materials\AI ONL 104\Data Preprocessing & Visulization\Pandas Practice assignment\Data\train.csv", encoding="ISO-8859-1")
df

Name    Location  Year  Kilometers_Driven  \
0                                 NaN      Mumbai  2010              72000   
1                                  na        Pune  2015              41000   
2                        Honda Jazz V     Chennai  2011              46000   
3                   Maruti Ertiga VDI     Chennai  2012              87000   
4     Audi A4 New 2.0 TDI Multitronic  Coimbatore  2013              40670   
...                               ...         ...   ...                ...   
6014                 Maruti Swift VDI       Delhi  2014              27365   
6015         Hyundai Xcent 1.1 CRDi S      Jaipur  2015             100000   
6016            Mahindra Xylo D4 BSIV      Jaipur  2012              55000   
6017               Maruti Wagon R VXI     Kolkata  2013              46000   
6018            Chevrolet Beat Diesel   Hyderabad  2011              47000   

     Fuel_Type Transmission Owner_Type     Mileage   Engine      Power  Seats  \
0          CNG       Manual      First  26.6 km/kg   998 CC  58.16 bhp    5.0   
1       Diesel       Manual      First  19.67 kmpl  1582 CC  126.2 bhp    5.0   
2       Petrol       Manual      First   18.2 kmpl  1199 CC   88.7 bhp    5.0   
3       Diesel       Manual      First  20.77 kmpl  1248 CC  88.76 bhp    7.0   
4       Diesel    Automatic     Second   15.2 kmpl  1968 CC  140.8 bhp    5.0   
...        ...          ...        ...         ...      ...        ...    ...   
6014    Diesel       Manual      First   28.4 kmpl  1248 CC     74 bhp    5.0   
6015    Diesel       Manual      First   24.4 kmpl  1120 CC     71 bhp    5.0   
6016    Diesel       Manual     Second   14.0 kmpl  2498 CC    112 bhp    8.0   
6017    Petrol       Manual      First   18.9 kmpl   998 CC   67.1 bhp    5.0   
6018    Diesel       Manual      First  25.44 kmpl   936 CC   57.6 bhp    5.0   

      New_Price  Price  
0           NaN   1.75  
1           NaN  12.50  
2     8.61 Lakh   4.50  
3           NaN   6.00  
4           NaN  17.74  
...         ...    ...  
6014  7.88 Lakh   4.75  
6015        NaN   4.00  
6016        NaN   2.90  
6017        NaN   2.65  
6018        NaN   2.50  

[6019 rows x 13 columns]

# part One

In [117]:
# 5 Min
df.shape

(6019, 13)

In [118]:
df.columns

Index(['Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'New_Price', 'Price'],
      dtype='object')

In [119]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Name               6018 non-null   object 
 1   Location           6019 non-null   object 
 2   Year               6019 non-null   int64  
 3   Kilometers_Driven  6019 non-null   int64  
 4   Fuel_Type          6019 non-null   object 
 5   Transmission       6019 non-null   object 
 6   Owner_Type         6019 non-null   object 
 7   Mileage            6017 non-null   object 
 8   Engine             5983 non-null   object 
 9   Power              5983 non-null   object 
 10  Seats              5977 non-null   float64
 11  New_Price          824 non-null    object 
 12  Price              6019 non-null   float64
dtypes: float64(2), int64(2), object(9)
memory usage: 611.4+ KB


In [120]:
df.describe()

Year  Kilometers_Driven        Seats        Price
count  6019.000000       6.019000e+03  5977.000000  6019.000000
mean   2013.358199       5.873838e+04     5.278735     9.479468
std       3.269742       9.126884e+04     0.808840    11.187917
min    1998.000000       1.710000e+02     0.000000     0.440000
25%    2011.000000       3.400000e+04     5.000000     3.500000
50%    2014.000000       5.300000e+04     5.000000     5.640000
75%    2016.000000       7.300000e+04     5.000000     9.950000
max    2019.000000       6.500000e+06    10.000000   160.000000

In [121]:
df.head()

Name    Location  Year  Kilometers_Driven  \
0                              NaN      Mumbai  2010              72000   
1                               na        Pune  2015              41000   
2                     Honda Jazz V     Chennai  2011              46000   
3                Maruti Ertiga VDI     Chennai  2012              87000   
4  Audi A4 New 2.0 TDI Multitronic  Coimbatore  2013              40670   

  Fuel_Type Transmission Owner_Type     Mileage   Engine      Power  Seats  \
0       CNG       Manual      First  26.6 km/kg   998 CC  58.16 bhp    5.0   
1    Diesel       Manual      First  19.67 kmpl  1582 CC  126.2 bhp    5.0   
2    Petrol       Manual      First   18.2 kmpl  1199 CC   88.7 bhp    5.0   
3    Diesel       Manual      First  20.77 kmpl  1248 CC  88.76 bhp    7.0   
4    Diesel    Automatic     Second   15.2 kmpl  1968 CC  140.8 bhp    5.0   

   New_Price  Price  
0        NaN   1.75  
1        NaN  12.50  
2  8.61 Lakh   4.50  
3        NaN   6.00  
4        NaN  17.74

# Data Cleaning


In [122]:
df.isnull().sum()

Name                    1
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 36
Power                  36
Seats                  42
New_Price            5195
Price                   0
dtype: int64

In [123]:
df = df.dropna(subset=['Name'])
df = df.dropna(subset=['Mileage'])
df = df.dropna(subset=['Engine'])
df = df.dropna(subset=['Power'])
df = df.dropna(subset=['Seats'])

In [124]:
df.isnull().sum()

Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 0
Engine                  0
Power                   0
Seats                   0
New_Price            5151
Price                   0
dtype: int64

In [125]:
# drop more than 5% missing values
df.drop(columns=['New_Price'], axis=1, inplace=True)

In [126]:
df.isnull().sum()

Name                 0
Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Mileage              0
Engine               0
Power                0
Seats                0
Price                0
dtype: int64

In [127]:
df

Name    Location  Year  Kilometers_Driven  \
1                                  na        Pune  2015              41000   
2                        Honda Jazz V     Chennai  2011              46000   
3                   Maruti Ertiga VDI     Chennai  2012              87000   
4     Audi A4 New 2.0 TDI Multitronic  Coimbatore  2013              40670   
5     Hyundai EON LPG Era Plus Option   Hyderabad  2012              75000   
...                               ...         ...   ...                ...   
6014                 Maruti Swift VDI       Delhi  2014              27365   
6015         Hyundai Xcent 1.1 CRDi S      Jaipur  2015             100000   
6016            Mahindra Xylo D4 BSIV      Jaipur  2012              55000   
6017               Maruti Wagon R VXI     Kolkata  2013              46000   
6018            Chevrolet Beat Diesel   Hyderabad  2011              47000   

     Fuel_Type Transmission Owner_Type     Mileage   Engine      Power  Seats  \
1       Diesel       Manual      First  19.67 kmpl  1582 CC  126.2 bhp    5.0   
2       Petrol       Manual      First   18.2 kmpl  1199 CC   88.7 bhp    5.0   
3       Diesel       Manual      First  20.77 kmpl  1248 CC  88.76 bhp    7.0   
4       Diesel    Automatic     Second   15.2 kmpl  1968 CC  140.8 bhp    5.0   
5          LPG       manual      First  21.1 km/kg   814 CC   55.2 bhp    5.0   
...        ...          ...        ...         ...      ...        ...    ...   
6014    Diesel       Manual      First   28.4 kmpl  1248 CC     74 bhp    5.0   
6015    Diesel       Manual      First   24.4 kmpl  1120 CC     71 bhp    5.0   
6016    Diesel       Manual     Second   14.0 kmpl  2498 CC    112 bhp    8.0   
6017    Petrol       Manual      First   18.9 kmpl   998 CC   67.1 bhp    5.0   
6018    Diesel       Manual      First  25.44 kmpl   936 CC   57.6 bhp    5.0   

      Price  
1     12.50  
2      4.50  
3      6.00  
4     17.74  
5      2.35  
...     ...  
6014   4.75  
6015   4.00  
6016   2.90  
6017   2.65  
6018   2.50  

[5974 rows x 12 columns]

In [128]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5974 entries, 1 to 6018
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Name               5974 non-null   object 
 1   Location           5974 non-null   object 
 2   Year               5974 non-null   int64  
 3   Kilometers_Driven  5974 non-null   int64  
 4   Fuel_Type          5974 non-null   object 
 5   Transmission       5974 non-null   object 
 6   Owner_Type         5974 non-null   object 
 7   Mileage            5974 non-null   object 
 8   Engine             5974 non-null   object 
 9   Power              5974 non-null   object 
 10  Seats              5974 non-null   float64
 11  Price              5974 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 606.7+ KB


In [129]:
df.duplicated().sum()

np.int64(0)

In [130]:
df['Name'].unique()

array(['na', 'Honda Jazz V', 'Maruti Ertiga VDI', ...,
       'Volkswagen Polo IPL II 1.2 Petrol Highline',
       'Tata Bolt Revotron XT', 'Mahindra Xylo D4 BSIV'], dtype=object)

In [131]:
df['Location'].unique()

array(['Pune', 'Chennai', 'Coimbatore', 'Hyderabad', 'Jaipur', 'Mumbai',
       'Kochi', 'Kolkata', 'Delhi', 'Bangalore', 'Ahmedabad'],
      dtype=object)

In [132]:
df['Year'].unique()

array([2015, 2011, 2012, 2013, 2016, 2018, 2014, 2017, 2010, 2007, 2009,
       2008, 2019, 2006, 2005, 2004, 2002, 2000, 2003, 1999, 2001, 1998])

In [133]:
df['Kilometers_Driven'].unique()

array([41000, 46000, 87000, ..., 45004, 70602, 27365])

In [134]:
df['Fuel_Type'].unique()

array(['Diesel', 'Petrol', 'LPG', 'CNG'], dtype=object)

In [135]:
df['Transmission'].unique()

array(['Manual', 'Automatic', 'manual'], dtype=object)

In [136]:
#replacing values
df['Transmission'] = df['Transmission'].replace([ 'manual'], 'Manual')

In [137]:
df['Transmission'].unique()

array(['Manual', 'Automatic'], dtype=object)

In [138]:
df.columns

Index(['Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'Price'],
      dtype='object')

In [139]:
df['Owner_Type'].unique()

array(['First', 'Second', 'Fourth & Above', 'Third'], dtype=object)

In [140]:
#df['Mileage'].unique()

In [141]:
#df['Engine'].unique()

In [142]:
#df['Power'].unique()

In [143]:
df['Seats'].unique()

array([ 5.,  7.,  8.,  4.,  6.,  2., 10.,  9.,  0.])

In [144]:
df['Price'].unique()

array([12.5 ,  4.5 ,  6.  , ...,  2.27, 17.56,  7.43])

In [145]:
df['Mileage'].unique()

array(['19.67 kmpl', '18.2 kmpl', '20.77 kmpl', '15.2 kmpl', '21.1 km/kg',
       '23.08 kmpl', '11.36 kmpl', '20.54 kmpl', '22.3 kmpl',
       '21.56 kmpl', '16.8 kmpl', '25.2 kmpl', '12.7 kmpl', '0.0 kmpl',
       '13.5 kmpl', '25.8 kmpl', '28.4 kmpl', '20.45 kmpl', '14.84 kmpl',
       '22.69 kmpl', '23.65 kmpl', '13.53 kmpl', '18.5 kmpl', '14.4 kmpl',
       '20.92 kmpl', '17.5 kmpl', '12.8 kmpl', '19.01 kmpl', '14.53 kmpl',
       '11.18 kmpl', '12.4 kmpl', '16.09 kmpl', '14.0 kmpl', '24.3 kmpl',
       '18.15 kmpl', '11.74 kmpl', '22.07 kmpl', '19.7 kmpl', '25.4 kmpl',
       '25.32 kmpl', '14.62 kmpl', '14.28 kmpl', '14.9 kmpl',
       '11.25 kmpl', '24.4 kmpl', '16.55 kmpl', '17.11 kmpl', '22.9 kmpl',
       '17.8 kmpl', '18.9 kmpl', '15.04 kmpl', '25.17 kmpl', '20.36 kmpl',
       '13.29 kmpl', '13.68 kmpl', '20.0 kmpl', '15.8 kmpl', '25.0 kmpl',
       '16.4 kmpl', '24.52 kmpl', '22.1 kmpl', '8.5 kmpl', '15.1 kmpl',
       '16.95 kmpl', '19.64 kmpl', '16.5 kmpl', '18.53 kmpl'

In [146]:
# Editing Mileage using apply function and change from km/kg to km/l
# km/l = 1.4 km/kg